### PR TITLE
Fix heading, improve package handling in docs

### LINKED ISSUE #19: Fix link to API in tutorial
image

The link to the API currently gives a '404 page not found error'. The API itself can be accessed, just not through this link.

### PR DESCRIPTION
**Pull request by dublinsubway**
Closes #19 ; the issue was in a different API heading. 
Another possible way to do it is to give it a unique name and reference it by the name, like so:
```
# OMOPCDMCohortCreator API[@id API]

here we reference [API](@ref API)
```
but imo it'll be a bit more tedious and time consuming. Also, tidied up a warning and made a failsafe to ensure module import.

If @TheCedarPrince has suggestions to edit it or he doesn't want to take the risk, just let me know! It's my first time with Julia, so things might me not up to par xd.

### CODE REVIEW

File: docs/make.jl [hunk 1]
```diff
@@ -1,6 +1,13 @@
...
 using Documenter
 
+try
+    using OMOPCDMCohortCreator
+catch
+    using Pkg
+    Pkg.add(url="github.com/JuliaHealth/OMOPCDMCohortCreator.jl", rev="main")
+    using OMOPCDMCohortCreator
+end
+
```
Comment (TheCedarPrince) [inline docs/make.jl:10]: I like where you are going with this but I am a bit curious - why do you think we need this? Did you run into issues with loading up the documentation locally on your side?

**Review by TheCedarPrince — COMMENTED** [review]
Hey @dublinsubway ! Great start for this PR! You laid out your logic and rationale quiet well and for a first time PR, GREAT job! :tada: Love the initiative!

So, as of this moment, technically, this PR does fix the documentation issue but what would actually be a bit better is using Documenter.jl (this part specifically: https://juliadocs.github.io/Documenter.jl/stable/man/guide/#Cross-Referencing) as that is what we use to host the documentation. In doing so, we'd get around the "tediousness" that you mentioned in your comment. Would you be wiling to work with me on adding Documenter referencing?

I know you said this is your first PR so happy to work/walk with you through it all. :smile:

File: docs/make.jl (hunk 1 above)
Comment (dublinsubway) [reply docs/make.jl:10]: It was tricky for me to start from scratch, as I aimed to just start Documenter and, of course, it was not willing to cooperate due to missing prerequisites.
If you think that's an overkill (and that could be one), we can leave it out.

**Comment by dublinsubway** [comment]
> So, as of this moment, technically, this PR does fix the documentation issue but what would actually be a bit better is using Documenter.jl (this part specifically: https://juliadocs.github.io/Documenter.jl/stable/man/guide/#Cross-Referencing) as that is what we use to host the documentation. In doing so, we'd get around the "tediousness" that you mentioned in your comment. Would you be wiling to work with me on adding Documenter referencing?

I can give a hand, but not sure what exactly you aim to achieve further: I consulted the API docs and there were no more warnings for invalid references while generating Documenter file, as name of the heading and the @ref to it aligned.

File: docs/make.jl (hunk 1 above)
Comment (TheCedarPrince) [reply docs/make.jl:10]: Yea - I will say let's leave this out. However, what were the missing prerequisites you ran into? Happy to help there.

**Comment by TheCedarPrince** [comment]
:man_facepalming: Haha, that is what I get when I do not check out your branch and test it locally! I see exactly what you did and how it works. It works perfectly and nothing else needs to be done here - we are free to merge! I am going to merge it into the `dev` branch for now as that is where the new release of this package will come from. Thanks @dublinsubway !
